# Generated by Django 4.2.30 on 2026-06-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science')], default='Python', max_length=50),
        ),
    ]
