# Generated by Django 4.2.30 on 2026-06-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_courses', models.IntegerField(default=0)),
                ('total_instructors', models.IntegerField(default=0)),
                ('total_enrollments', models.IntegerField(default=0)),
            ],
        ),
    ]
